DROP COLUMN TABLE "SALES_ORDER"

DROP COLUMN TABLE "SALES_ORDER_ITEM"

CREATE COLUMN TABLE "MATERIAL" (
	"MATERIAL" VARCHAR(20) NOT NULL,
	"DESCRIPTION" VARCHAR(50),
	"BASE_UOM" VARCHAR(3),
	"PRICE" DECIMAL(15,2) CS_FIXED,
	PRIMARY KEY ("MATERIAL")
) UNLOAD PRIORITY 5 AUTO MERGE 

CREATE COLUMN TABLE "CUSTOMER" (
	"CUSTOMER" VARCHAR(10) NOT NULL,
	"DESCRIPTION" VARCHAR(50),
	PRIMARY KEY ("CUSTOMER")
) UNLOAD PRIORITY 5 AUTO MERGE

CREATE COLUMN TABLE "UNIT_OF_MEASURE" (
	"UOM" VARCHAR(3) NOT NULL,
	"DESCRIPTION" VARCHAR(50),
	PRIMARY KEY ("CUSTOMER")
) UNLOAD PRIORITY 5 AUTO MERGE

CREATE COLUMN TABLE "MYORDERS"."SALES_ORDER" (
    "TENANT_ID" INTEGER CS_INT NOT NULL,
	"SALES_ORDER" VARCHAR(10) NOT NULL,
	"CUSTOMER" VARCHAR(10),
	"ORDER_DATE" DATE CS_DAYDATE,
	"STATUS" VARCHAR(10),
	"COMMENT" VARCHAR(50),
	"ORDER_TOTAL_GROSS" DECIMAL(15,2) CS_FIXED,
	"CURRENCY" VARCHAR(3),
	"UODATE_FLAG" CHAR(1),
	PRIMARY KEY ("SALES_ORDER", "TENANT_ID")
) UNLOAD PRIORITY 5 AUTO MERGE 
	 
CREATE COLUMN TABLE "MYORDERS"."SALES_ORDER_ITEM" (
	"TENANT_ID" INTEGER CS_INT NOT NULL,
	"SALES_ORDER" VARCHAR(10) NOT NULL,
	"SALES_ORDER_ITEM" VARCHAR(5) NOT NULL ,
	"MATERIAL" VARCHAR(20) NOT NULL ,
	"QUANTITY" DECIMAL(15,2) CS_FIXED,
	"PRICE" DECIMAL(15,2) CS_FIXED,
	"AMOUNT_GROSS" DECIMAL(15,2),
	"ORDER_UOM" VARCHAR(3) NOT NULL ,
	"UODATE_FLAG" CHAR(1),
	PRIMARY KEY INVERTED VALUE ("SALES_ORDER", "SALES_ORDER_ITEM","TENANT_ID")
) UNLOAD PRIORITY 5 AUTO MERGE 

insert into "MYORDERS"."TENANT" values(1,'sokolovskij-yurij@yandex.ru')
insert into "MYORDERS"."SALES_ORDER" values(1,'1000000000','123','01.10.2017','SHP','My test order',1000,'RUB')
insert into "MYORDERS"."MATERIAL" values('M000001','Test Material 1', 'PC')
insert into "MYORDERS"."MATERIAL" values('M000002','Test Material 2', 'PC')
insert into "MYORDERS"."MATERIAL" values('M000003','Test Material 3', 'PC')

insert into "MYORDERS"."CUSTOMER" values('14000001','Test Client 1')
insert into "MYORDERS"."CUSTOMER" values('14000002','Test Client 2')
insert into "MYORDERS"."CUSTOMER" values('14000003','Test Client 3')

insert into "MYORDERS"."SALES_ORDER_ITEM" values(1,'1000000000','010','MAT01', 1, 100, 100,'PC')
insert into "MYORDERS"."SALES_ORDER_ITEM" values(1,'1000000000','020','MAT02', 1, 100, 100,'PC')

insert into "MYORDERS"."UNIT_OF_MEASURE" values('PC', 'Piece')
insert into "MYORDERS"."UNIT_OF_MEASURE" values('KG', 'Kilogramm')
